### ISSUE TITLE
Improvement in your instructions

### ISSUE THREAD

**Issue by zorgrian** [timmeinerzhagen/mkdocs-meta-manager#14]
# Please help 
It is not obvious how to use this plugin. I need this plugin as the material for MKDOCS built-in plugin no longer works at all!

In your readme.md file, you say that these YAML pairs will work.

```yml

meta_filename Change the default name of the meta file. (default=.meta.yml)

merge_tags Merge the tags of all relevant meta files and pages for a page (default=false)

```

However, it would be helpful if you could say how these modifiers (YAML pairs) are used within the `mkdocs.yml` file.

**Comment by timmeinerzhagen** [comment]
Hi @zorgrian 

It would look like this

```yaml
plugins:
    - search
    - meta-manager:
        meta_filename: "tags.yml"
        merge_tags: true
```
